# Generated by Django 6.0.1 on 2026-01-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='is_completd',
            new_name='is_completed',
        ),
    ]
